[build]
beforeDevCommand = "yarn dev"
beforeBuildCommand = "yarn build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = true

[package]
productName = "filespider"
version = "2.0.0-alpha"

[tauri.allowlist]
all = false
shell = { all = false, open = true }
protocol = { all = false, asset = true }
fs = { readFile = true }

[tauri.bundle]
active = true
targets = "all"
identifier = "me.kruemmelspalter.filespider"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]

[tauri.security]
csp = "default-src 'self'; img-src 'self' asset: https://asset.localhost"

[[tauri.windows]]
fullscreen = false
resizable = true
title = "FileSpider"
width = 800
height = 600

[tauri.allowlist.dialog]
open = true
