/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.kruemmelspalter.file_spider.backend

import me.kruemmelspalter.file_spider.backend.api.FileSpiderApplication

fun main() {
    FileSpiderApplication.run(arrayOf(""))
}
