version: '3'

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.31.69.0/24

services:
    database:
        image: mariadb
        environment:
            MARIADB_DATABASE: database
            MARIADB_USER: user
            MARIADB_PASSWORD: password
            MARIADB_ROOT_HOST: localhost
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        expose:
            - 3306
        volumes:
            - ./data/mysql:/var/lib/mysql
  
    backend:
        image: ghcr.io/kruemmelspalter/filespider-backend:${FILESPIDER_TAG}
        environment:
            APP_OPTS: |
                -Ddatabase.host=database
                -Ddatabase.username=user
                -Ddatabase.password=password
                -Ddatabase.database=database
                -Dlogging.level.org.apache.tomcat.util.net.NioEndpoint=INFO
                -Dlogging.level.org.apache.catalina.session.ManagerBase=INFO
                -Dlogging.level.org.apache.coyote.http11.Http11Processor=INFO
                -Dlogging.level.root=INFO # change according to needs
        volumes:
            - ./data/filespider:/var/lib/filespider
        depends_on:
            database_started:
                condition: service_completed_successfully

    frontend:
        image: ghcr.io/kruemmelspalter/filespider-frontend:${FILESPIDER_TAG}

    database_started:
        image: dadarek/wait-for-dependencies
        depends_on:
            - database
        command: database:3306

    backend_started:
        image: dadarek/wait-for-dependencies
        depends_on:
            - backend
        command: backend:80

    frontend_started:
            image: dadarek/wait-for-dependencies
            depends_on:
                - frontend
            command: frontend:80

    reverse-proxy:
        image: vizshrc/nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./data/filespider:/data/filespider
        depends_on:
            backend_started:
                condition: service_completed_successfully
            frontend_started:
                condition: service_completed_successfully
