name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]

    runs-on: ubuntu-latest # ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: rust-${{ runner.os }}-$(rustc --version 2>&1|sed -E 's/^rustc [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ \(([[:digit:][:lower:]]+) [[:digit:]]+-[[:digit:]]+-[[:digit:]]+\)$/\1/')-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get update && sudo apt-get install libgtk-3-dev libsoup2.4-dev
      - run: cargo install tauri-cli
      - run: yarn install
      - run: cargo tauri build
      - uses: actions/upload-artifact@v3
        with:
          path: |
            src-tauri/target/release/filespider-*.deb
            src-tauri/target/release/filespider-*.appimage
