name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - id: versions
        run: |
          echo "rust=$(rustc --version 2>&1|sed -E 's/^rustc [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ \(([[:digit:][:lower:]]+) [[:digit:]]+-[[:digit:]]+-[[:digit:]]+\)$/\1/')" >> $GITHUB_OUTPUT
          echo "yarncachedir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: rust-${{ runner.os }}-${{ steps.versions.outputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.versions.outputs.yarncachedir }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock')}}

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        if: matrix.os == 'windows-latest'

      - run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}

      - run: cargo install tauri-cli
        if: steps.rust-cache.outputs.cache-hit != 'true'
      - run: yarn install

      - run: cargo tauri build

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        name: ${{ matrix.os }}-${{ matrix.rust }}.deb
        with:
          path: |
            src-tauri/target/release/bundle/deb/filespider_*.deb
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        name: ${{ matrix.os }}-${{ matrix.rust }}.appimage
        with:
          path: |
            src-tauri/target/release/bundle/appimage/filespider_*.appimage

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.os }}-${{ matrix.rust }}.msi
          path: |
            src-tauri/target/release/bundle/msi/filespider_*.msi
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.os }}-${{ matrix.rust }}.exe
          path: |
            src-tauri/target/release/bundle/nsis/filespider_*-setup.exe
