name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash

    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        if: matrix.os == 'windows-latest'

      - run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}-x86_64-pc-windows-gnu
        if: matrix.os == 'windows-latest'

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
        if: matrix.os == 'ubuntu-latest'

      - uses: rui314/setup-mold@v1

      - run: cargo install tauri-cli
        if: steps.rust-cache.outputs.cache-hit != 'true'
      - run: yarn install

      - run: cargo tauri build
        env:
          RUST_BACKTRACE: full

      - if: matrix.os == 'ubuntu-latest'
        run: |
          mv src-tauri/target/release/bundle/deb/filespider_*.deb filespider-${{matrix.rust}}.deb
          mv src-tauri/target/release/bundle/appimage/filespider_*.AppImage filespider-${{matrix.rust}}.AppImage

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        name: filespider-${{matrix.rust}}.deb
        with:
          path: filespider-${{matrix.rust}}.deb
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        name: filespider-${{matrix.rust}}.AppImage
        with:
          path: filespider-${{matrix.rust}}.AppImage

      - if: matrix.os == 'windows-latest'
        run: |
          ls src-tauri/target/release/bundle/{msi,nsis} 
          mv src-tauri/target/release/bundle/msi/filespider_*.msi filespider-${{matrix.rust}}.msi
          mv src-tauri/target/release/bundle/nsis/filespider_*-setup.exe filespider-${{matrix.rust}}.exe

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        name: filespider-${{matrix.rust}}.msi
        with:
          path: filespider-${{matrix.rust}}.msi
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        name: filespider-${{matrix.rust}}.msi
        with:
          path: filespider-${{matrix.rust}}.exe
