name: Docker CI

on:
    - push

jobs:
    push:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [lts/*]
                    
        steps:
            - uses: actions/checkout@v3
            - uses: docker/login-action@v2
              with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GH_PAT }}
            - uses: docker/setup-buildx-action@v1
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            
            - name: Cache node_modules
              uses: actions/cache@v3
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-
            
            - run: cd frontend && yarn
            - run: make -C frontend build
            - run: make app/build/distributions/app.tar
            - uses: docker/build-push-action@v2
              with:
                context: backend
                images: ghcr.io/kruemmelspalter/filespider-backend
                tags: |
                    type=semver,pattern={{version}}
                    type=ref,event=branch
                    type=ref,event=tag
                    type=sha
                    type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                    type=edge
